APT::FTPArchive::Release {
  Origin "AJLinux";
  Label "AJLinux";
  Suite "stable";
  Codename "stable";
  Version "1.0";
  Architectures "amd64";
  Components "main";
  Description "AJLinux APT Repository";
};
